# Generated by Django 6.0.2 on 2026-02-10 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('supervisor', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'leave_user',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leaveId', models.AutoField(primary_key=True, serialize=False)),
                ('from', models.DateField()),
                ('to', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('emergencyContact', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_leave',
            },
        ),
    ]
