# Generated by Django 6.0.2 on 2026-02-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
