# Generated by Django 6.0.2 on 2026-02-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leaveId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
