# Generated by Django 6.0.2 on 2026-02-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_leave_leaveid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='user',
            new_name='userId',
        ),
    ]
